### ISSUE TITLE
Starting animation directing users to the start point

### ISSUE THREAD

**Issue by andymasteroffish** [andymasteroffish/hardware_jam#1]
I wonder if when a new round starts, there should be an animation leading to where the players actually start so folks know where to look

**Comment by sabotai** [comment]
I think this sounds nice. If we can get the 5 rows working, we could have text welcoming the players. A button could be used to cycle through number of players too.

**Comment by sabotai** [comment]
I made something we could potentially use in the future in the Processing version. Right now it displays "GO" surrounded by arrows moving to the starting point. This could be used when the game starts.
